// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hoover.proto

/*
Package hoover is a generated protocol buffer package.

It is generated from these files:
	hoover.proto

It has these top-level messages:
	GetRequest
	GetReply
*/
package hoover

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptorHoover, []int{0} }

func (m *GetRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetReply struct {
	ResponseCode int32                     `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Body         string                    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Elapsed      *google_protobuf.Duration `protobuf:"bytes,3,opt,name=elapsed" json:"elapsed,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptorHoover, []int{1} }

func (m *GetReply) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *GetReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetReply) GetElapsed() *google_protobuf.Duration {
	if m != nil {
		return m.Elapsed
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "hoover.GetRequest")
	proto.RegisterType((*GetReply)(nil), "hoover.GetReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := grpc.Invoke(ctx, "/hoover.Service/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hoover.Service/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hoover.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Service_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hoover.proto",
}

func init() { proto.RegisterFile("hoover.proto", fileDescriptorHoover) }

var fileDescriptorHoover = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xd1, 0x56, 0xc7, 0x0a, 0x65, 0x4e, 0xb1, 0x87, 0x52, 0xe2, 0xa5, 0x17, 0xb7,
	0xd0, 0x5c, 0xbc, 0x2b, 0xe4, 0xbe, 0x7e, 0x00, 0x49, 0xb2, 0x63, 0x0c, 0x2c, 0x99, 0x75, 0xff,
	0x04, 0xf3, 0xed, 0xc5, 0x4d, 0x82, 0x78, 0x7b, 0xfb, 0xf6, 0xc7, 0xe3, 0x37, 0xb0, 0xf9, 0x64,
	0x1e, 0xc8, 0x0a, 0x63, 0xd9, 0x33, 0xae, 0xa6, 0xd7, 0x6e, 0xdf, 0x32, 0xb7, 0x9a, 0x4e, 0xb1,
	0xad, 0xc3, 0xc7, 0x49, 0x05, 0x5b, 0xf9, 0x8e, 0xfb, 0x89, 0xcb, 0xf7, 0x00, 0x25, 0x79, 0x49,
	0x5f, 0x81, 0x9c, 0xc7, 0x2d, 0xa4, 0xc1, 0xea, 0x2c, 0x39, 0x24, 0xc7, 0x5b, 0xf9, 0x1b, 0xf3,
	0x6f, 0xb8, 0x89, 0xff, 0x46, 0x8f, 0xf8, 0x08, 0xf7, 0x96, 0x9c, 0xe1, 0xde, 0xd1, 0x7b, 0xc3,
	0x8a, 0x22, 0x77, 0x2d, 0x37, 0x4b, 0xf9, 0xc2, 0x8a, 0x10, 0xe1, 0xaa, 0x66, 0x35, 0x66, 0x97,
	0x71, 0x23, 0x66, 0x2c, 0x60, 0x4d, 0xba, 0x32, 0x8e, 0x54, 0x96, 0x1e, 0x92, 0xe3, 0xdd, 0xf9,
	0x41, 0x4c, 0x5a, 0x62, 0xd1, 0x12, 0xaf, 0xb3, 0x96, 0x5c, 0xc8, 0xf3, 0x33, 0xac, 0xdf, 0xc8,
	0x0e, 0x5d, 0x43, 0xf8, 0x04, 0x69, 0x49, 0x1e, 0x51, 0xcc, 0x27, 0xfe, 0x19, 0xef, 0xb6, 0xff,
	0x3a, 0xa3, 0xc7, 0xfc, 0xa2, 0x5e, 0xc5, 0xd5, 0xe2, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x97,
	0x93, 0xe4, 0x12, 0x01, 0x00, 0x00,
}
