// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: codes.proto

/*
Package codes is a generated protocol buffer package.

It is generated from these files:
	codes.proto

It has these top-level messages:
*/
package codes

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Code int32

const (
	Code_OK       Code = 0
	Code_NotFound Code = 1
	Code_Unknown  Code = 2
)

var Code_name = map[int32]string{
	0: "OK",
	1: "NotFound",
	2: "Unknown",
}
var Code_value = map[string]int32{
	"OK":       0,
	"NotFound": 1,
	"Unknown":  2,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}
func (Code) EnumDescriptor() ([]byte, []int) { return fileDescriptorCodes, []int{0} }

func init() {
	proto.RegisterEnum("codes.Code", Code_name, Code_value)
}

func init() { proto.RegisterFile("codes.proto", fileDescriptorCodes) }

var fileDescriptorCodes = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0x4f, 0x49,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xb4, 0x34, 0xb9, 0x58, 0x9c,
	0xf3, 0x53, 0x52, 0x85, 0xd8, 0xb8, 0x98, 0xfc, 0xbd, 0x05, 0x18, 0x84, 0x78, 0xb8, 0x38, 0xfc,
	0xf2, 0x4b, 0xdc, 0xf2, 0x4b, 0xf3, 0x52, 0x04, 0x18, 0x85, 0xb8, 0xb9, 0xd8, 0x43, 0xf3, 0xb2,
	0xf3, 0xf2, 0xcb, 0xf3, 0x04, 0x98, 0x92, 0xd8, 0xc0, 0x1a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf5, 0xc5, 0x2a, 0xa3, 0x47, 0x00, 0x00, 0x00,
}
